version: '2'
services:
  base:
    build: .
    image: ropelive/count
    restart: on-failure
    volumes:
    - .:/go/src/github.com/ropelive/count
    - logvolume01:/var/log


  counter:
    extends: base
    ports:
    - "8080:8080"
    command: /go/bin/counter --http.addr :8080 --redis.addr redis:6379
    links:
    - redis
    - mongo

  compactor:
    extends: base
    ports:
    - "8081:8081"
    command: /go/bin/compactor --http.addr :8081 --redis.addr redis:6379 --mongo.addr "mongodb://mongo:27017"
    links:
    - redis
    - mongo

  redis:
    image: redis:4.0.5
    ports:
      - "6379:6379"

  mongo:
    image: mongo:3.0.15
    ports:
      - "27017:27017"

volumes:
  logvolume01: {}