apiVersion: v1
kind: Service
metadata:
  name: counter
  namespace: default
  labels:
    name: counter
    service: counter
    app: counter
spec:
  type: LoadBalancer
  selector:
    name: counter
  ports:
    - name: http
      port: 8080
      targetPort: 8080

---

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: counter
  namespace: default
  labels:
    name: counter
    service: counter
    app: counter
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: counter
        service: counter
        app: counter
    spec:
      containers:
      - image: koding/ropecount_base
        name: counter
        command:
        - "/go/bin/counter"
        - "--http.addr"
        - ":8080"
        - "--redis.addr"
        - "redis1-redis:6379"
        ports:
        - name: http
          containerPort: 8080